# Generated by Django 5.0.4 on 2024-04-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabletimeslot',
            name='date',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='available_timeslots',
            field=models.ManyToManyField(null=True, to='schedule.availabletimeslot'),
        ),
    ]
