# Generated by Django 5.0.4 on 2024-04-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_remove_availabletimeslot_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='room',
            field=models.IntegerField(choices=[(1, 'Зал 1'), (2, 'Зал 2'), (3, 'Зал 3')], null=True),
        ),
        migrations.AlterField(
            model_name='availabletimeslot',
            name='room',
            field=models.IntegerField(choices=[(1, 'Зал 1'), (2, 'Зал 2'), (3, 'Зал 3')], null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='available_timeslots',
            field=models.ManyToManyField(to='schedule.availabletimeslot'),
        ),
        migrations.AlterUniqueTogether(
            name='availabletimeslot',
            unique_together={('timeslot', 'weekday', 'room')},
        ),
    ]
