# Generated by Django 5.0.4 on 2024-04-05 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_appointment_room_alter_availabletimeslot_room_and_more'),
        ('trainer', '0003_trainer_description_trainer_education_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('trainer', 'date', 'timeslot', 'room', 'client')},
        ),
    ]
