# Generated by Django 5.0.4 on 2024-04-05 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_alter_appointment_unique_together'),
        ('trainer', '0003_trainer_description_trainer_education_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('date', 'timeslot', 'client'), ('date', 'timeslot', 'trainer'), ('trainer', 'date', 'timeslot', 'room')},
        ),
    ]
